// ═══════════════════════════════════════════════════════════════════════════
// TableQuizz - French Conjugation Data
// ═══════════════════════════════════════════════════════════════════════════

const PRONOUNS = [
  { fr: "je", en: "I", elided: "j'" },
  { fr: "tu", en: "you (informal)", elided: null },
  { fr: "il/elle/on", en: "he/she/one", elided: null },
  { fr: "nous", en: "we", elided: null },
  { fr: "vous", en: "you (formal/pl.)", elided: null },
  { fr: "ils/elles", en: "they", elided: null },
];

const TENSES = {
  present: {
    name: "Présent",
    nameEn: "Present",
    description: "Actions happening now, habits, general truths",
    descriptionFr: "Actions actuelles, habitudes, vérités générales",
    color: "#f8bbd9",
  },
  passeCompose: {
    name: "Passé composé",
    nameEn: "Past (completed)",
    description: "Completed actions in the past",
    descriptionFr: "Actions terminées dans le passé",
    color: "#ce93d8",
  },
  imparfait: {
    name: "Imparfait",
    nameEn: "Imperfect",
    description: "Ongoing or habitual past actions, descriptions",
    descriptionFr: "Actions continues ou habituelles dans le passé",
    color: "#b39ddb",
  },
  futurSimple: {
    name: "Futur simple",
    nameEn: "Future",
    description: "Actions that will happen",
    descriptionFr: "Actions qui vont se produire",
    color: "#90caf9",
  },
  conditionnelPresent: {
    name: "Conditionnel présent",
    nameEn: "Conditional",
    description: "Would do something, polite requests",
    descriptionFr: "Actions conditionnelles, demandes polies",
    color: "#80deea",
  },
  subjonctifPresent: {
    name: "Subjonctif présent",
    nameEn: "Subjunctive",
    description: "Wishes, doubts, emotions, necessities",
    descriptionFr: "Souhaits, doutes, émotions, nécessités",
    color: "#a5d6a7",
  },
};

const VERBS = {
  etre: {
    infinitive: "être",
    english: "to be",
    group: "Irregular",
    importance: 1,
    tenses: {
      present: ["suis", "es", "est", "sommes", "êtes", "sont"],
      passeCompose: ["ai été", "as été", "a été", "avons été", "avez été", "ont été"],
      imparfait: ["étais", "étais", "était", "étions", "étiez", "étaient"],
      futurSimple: ["serai", "seras", "sera", "serons", "serez", "seront"],
      conditionnelPresent: ["serais", "serais", "serait", "serions", "seriez", "seraient"],
      subjonctifPresent: ["sois", "sois", "soit", "soyons", "soyez", "soient"],
    },
  },
  avoir: {
    infinitive: "avoir",
    english: "to have",
    group: "Irregular",
    importance: 1,
    startsWithVowel: true,
    tenses: {
      present: ["ai", "as", "a", "avons", "avez", "ont"],
      passeCompose: ["ai eu", "as eu", "a eu", "avons eu", "avez eu", "ont eu"],
      imparfait: ["avais", "avais", "avait", "avions", "aviez", "avaient"],
      futurSimple: ["aurai", "auras", "aura", "aurons", "aurez", "auront"],
      conditionnelPresent: ["aurais", "aurais", "aurait", "aurions", "auriez", "auraient"],
      subjonctifPresent: ["aie", "aies", "ait", "ayons", "ayez", "aient"],
    },
  },
  aller: {
    infinitive: "aller",
    english: "to go",
    group: "Irregular",
    importance: 2,
    startsWithVowel: true,
    usesEtre: true,
    tenses: {
      present: ["vais", "vas", "va", "allons", "allez", "vont"],
      passeCompose: ["suis allé(e)", "es allé(e)", "est allé(e)", "sommes allé(e)s", "êtes allé(e)(s)", "sont allé(e)s"],
      imparfait: ["allais", "allais", "allait", "allions", "alliez", "allaient"],
      futurSimple: ["irai", "iras", "ira", "irons", "irez", "iront"],
      conditionnelPresent: ["irais", "irais", "irait", "irions", "iriez", "iraient"],
      subjonctifPresent: ["aille", "ailles", "aille", "allions", "alliez", "aillent"],
    },
  },
  faire: {
    infinitive: "faire",
    english: "to do / to make",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["fais", "fais", "fait", "faisons", "faites", "font"],
      passeCompose: ["ai fait", "as fait", "a fait", "avons fait", "avez fait", "ont fait"],
      imparfait: ["faisais", "faisais", "faisait", "faisions", "faisiez", "faisaient"],
      futurSimple: ["ferai", "feras", "fera", "ferons", "ferez", "feront"],
      conditionnelPresent: ["ferais", "ferais", "ferait", "ferions", "feriez", "feraient"],
      subjonctifPresent: ["fasse", "fasses", "fasse", "fassions", "fassiez", "fassent"],
    },
  },
  pouvoir: {
    infinitive: "pouvoir",
    english: "can / to be able to",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"],
      passeCompose: ["ai pu", "as pu", "a pu", "avons pu", "avez pu", "ont pu"],
      imparfait: ["pouvais", "pouvais", "pouvait", "pouvions", "pouviez", "pouvaient"],
      futurSimple: ["pourrai", "pourras", "pourra", "pourrons", "pourrez", "pourront"],
      conditionnelPresent: ["pourrais", "pourrais", "pourrait", "pourrions", "pourriez", "pourraient"],
      subjonctifPresent: ["puisse", "puisses", "puisse", "puissions", "puissiez", "puissent"],
    },
  },
  vouloir: {
    infinitive: "vouloir",
    english: "to want",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["veux", "veux", "veut", "voulons", "voulez", "veulent"],
      passeCompose: ["ai voulu", "as voulu", "a voulu", "avons voulu", "avez voulu", "ont voulu"],
      imparfait: ["voulais", "voulais", "voulait", "voulions", "vouliez", "voulaient"],
      futurSimple: ["voudrai", "voudras", "voudra", "voudrons", "voudrez", "voudront"],
      conditionnelPresent: ["voudrais", "voudrais", "voudrait", "voudrions", "voudriez", "voudraient"],
      subjonctifPresent: ["veuille", "veuilles", "veuille", "voulions", "vouliez", "veuillent"],
    },
  },
  devoir: {
    infinitive: "devoir",
    english: "must / to have to",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["dois", "dois", "doit", "devons", "devez", "doivent"],
      passeCompose: ["ai dû", "as dû", "a dû", "avons dû", "avez dû", "ont dû"],
      imparfait: ["devais", "devais", "devait", "devions", "deviez", "devaient"],
      futurSimple: ["devrai", "devras", "devra", "devrons", "devrez", "devront"],
      conditionnelPresent: ["devrais", "devrais", "devrait", "devrions", "devriez", "devraient"],
      subjonctifPresent: ["doive", "doives", "doive", "devions", "deviez", "doivent"],
    },
  },
  savoir: {
    infinitive: "savoir",
    english: "to know (fact)",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["sais", "sais", "sait", "savons", "savez", "savent"],
      passeCompose: ["ai su", "as su", "a su", "avons su", "avez su", "ont su"],
      imparfait: ["savais", "savais", "savait", "savions", "saviez", "savaient"],
      futurSimple: ["saurai", "sauras", "saura", "saurons", "saurez", "sauront"],
      conditionnelPresent: ["saurais", "saurais", "saurait", "saurions", "sauriez", "sauraient"],
      subjonctifPresent: ["sache", "saches", "sache", "sachions", "sachiez", "sachent"],
    },
  },
  venir: {
    infinitive: "venir",
    english: "to come",
    group: "Irregular",
    importance: 2,
    usesEtre: true,
    tenses: {
      present: ["viens", "viens", "vient", "venons", "venez", "viennent"],
      passeCompose: ["suis venu(e)", "es venu(e)", "est venu(e)", "sommes venu(e)s", "êtes venu(e)(s)", "sont venu(e)s"],
      imparfait: ["venais", "venais", "venait", "venions", "veniez", "venaient"],
      futurSimple: ["viendrai", "viendras", "viendra", "viendrons", "viendrez", "viendront"],
      conditionnelPresent: ["viendrais", "viendrais", "viendrait", "viendrions", "viendriez", "viendraient"],
      subjonctifPresent: ["vienne", "viennes", "vienne", "venions", "veniez", "viennent"],
    },
  },
  prendre: {
    infinitive: "prendre",
    english: "to take",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["prends", "prends", "prend", "prenons", "prenez", "prennent"],
      passeCompose: ["ai pris", "as pris", "a pris", "avons pris", "avez pris", "ont pris"],
      imparfait: ["prenais", "prenais", "prenait", "prenions", "preniez", "prenaient"],
      futurSimple: ["prendrai", "prendras", "prendra", "prendrons", "prendrez", "prendront"],
      conditionnelPresent: ["prendrais", "prendrais", "prendrait", "prendrions", "prendriez", "prendraient"],
      subjonctifPresent: ["prenne", "prennes", "prenne", "prenions", "preniez", "prennent"],
    },
  },
  parler: {
    infinitive: "parler",
    english: "to speak",
    group: "1st group (-er)",
    importance: 3,
    tenses: {
      present: ["parle", "parles", "parle", "parlons", "parlez", "parlent"],
      passeCompose: ["ai parlé", "as parlé", "a parlé", "avons parlé", "avez parlé", "ont parlé"],
      imparfait: ["parlais", "parlais", "parlait", "parlions", "parliez", "parlaient"],
      futurSimple: ["parlerai", "parleras", "parlera", "parlerons", "parlerez", "parleront"],
      conditionnelPresent: ["parlerais", "parlerais", "parlerait", "parlerions", "parleriez", "parleraient"],
      subjonctifPresent: ["parle", "parles", "parle", "parlions", "parliez", "parlent"],
    },
  },
  finir: {
    infinitive: "finir",
    english: "to finish",
    group: "2nd group (-ir)",
    importance: 3,
    tenses: {
      present: ["finis", "finis", "finit", "finissons", "finissez", "finissent"],
      passeCompose: ["ai fini", "as fini", "a fini", "avons fini", "avez fini", "ont fini"],
      imparfait: ["finissais", "finissais", "finissait", "finissions", "finissiez", "finissaient"],
      futurSimple: ["finirai", "finiras", "finira", "finirons", "finirez", "finiront"],
      conditionnelPresent: ["finirais", "finirais", "finirait", "finirions", "finiriez", "finiraient"],
      subjonctifPresent: ["finisse", "finisses", "finisse", "finissions", "finissiez", "finissent"],
    },
  },
  manger: {
    infinitive: "manger",
    english: "to eat",
    group: "1st group (-er)",
    importance: 3,
    tenses: {
      present: ["mange", "manges", "mange", "mangeons", "mangez", "mangent"],
      passeCompose: ["ai mangé", "as mangé", "a mangé", "avons mangé", "avez mangé", "ont mangé"],
      imparfait: ["mangeais", "mangeais", "mangeait", "mangions", "mangiez", "mangeaient"],
      futurSimple: ["mangerai", "mangeras", "mangera", "mangerons", "mangerez", "mangeront"],
      conditionnelPresent: ["mangerais", "mangerais", "mangerait", "mangerions", "mangeriez", "mangeraient"],
      subjonctifPresent: ["mange", "manges", "mange", "mangions", "mangiez", "mangent"],
    },
  },
  voir: {
    infinitive: "voir",
    english: "to see",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["vois", "vois", "voit", "voyons", "voyez", "voient"],
      passeCompose: ["ai vu", "as vu", "a vu", "avons vu", "avez vu", "ont vu"],
      imparfait: ["voyais", "voyais", "voyait", "voyions", "voyiez", "voyaient"],
      futurSimple: ["verrai", "verras", "verra", "verrons", "verrez", "verront"],
      conditionnelPresent: ["verrais", "verrais", "verrait", "verrions", "verriez", "verraient"],
      subjonctifPresent: ["voie", "voies", "voie", "voyions", "voyiez", "voient"],
    },
  },
  dire: {
    infinitive: "dire",
    english: "to say / to tell",
    group: "Irregular",
    importance: 2,
    tenses: {
      present: ["dis", "dis", "dit", "disons", "dites", "disent"],
      passeCompose: ["ai dit", "as dit", "a dit", "avons dit", "avez dit", "ont dit"],
      imparfait: ["disais", "disais", "disait", "disions", "disiez", "disaient"],
      futurSimple: ["dirai", "diras", "dira", "dirons", "direz", "diront"],
      conditionnelPresent: ["dirais", "dirais", "dirait", "dirions", "diriez", "diraient"],
      subjonctifPresent: ["dise", "dises", "dise", "disions", "disiez", "disent"],
    },
  },
  aimer: {
    infinitive: "aimer",
    english: "to love / to like",
    group: "1st group (-er)",
    importance: 3,
    startsWithVowel: true,
    tenses: {
      present: ["aime", "aimes", "aime", "aimons", "aimez", "aiment"],
      passeCompose: ["ai aimé", "as aimé", "a aimé", "avons aimé", "avez aimé", "ont aimé"],
      imparfait: ["aimais", "aimais", "aimait", "aimions", "aimiez", "aimaient"],
      futurSimple: ["aimerai", "aimeras", "aimera", "aimerons", "aimerez", "aimeront"],
      conditionnelPresent: ["aimerais", "aimerais", "aimerait", "aimerions", "aimeriez", "aimeraient"],
      subjonctifPresent: ["aime", "aimes", "aime", "aimions", "aimiez", "aiment"],
    },
  },
  partir: {
    infinitive: "partir",
    english: "to leave",
    group: "Irregular",
    importance: 3,
    usesEtre: true,
    tenses: {
      present: ["pars", "pars", "part", "partons", "partez", "partent"],
      passeCompose: ["suis parti(e)", "es parti(e)", "est parti(e)", "sommes parti(e)s", "êtes parti(e)(s)", "sont parti(e)s"],
      imparfait: ["partais", "partais", "partait", "partions", "partiez", "partaient"],
      futurSimple: ["partirai", "partiras", "partira", "partirons", "partirez", "partiront"],
      conditionnelPresent: ["partirais", "partirais", "partirait", "partirions", "partiriez", "partiraient"],
      subjonctifPresent: ["parte", "partes", "parte", "partions", "partiez", "partent"],
    },
  },
  mettre: {
    infinitive: "mettre",
    english: "to put",
    group: "Irregular",
    importance: 3,
    tenses: {
      present: ["mets", "mets", "met", "mettons", "mettez", "mettent"],
      passeCompose: ["ai mis", "as mis", "a mis", "avons mis", "avez mis", "ont mis"],
      imparfait: ["mettais", "mettais", "mettait", "mettions", "mettiez", "mettaient"],
      futurSimple: ["mettrai", "mettras", "mettra", "mettrons", "mettrez", "mettront"],
      conditionnelPresent: ["mettrais", "mettrais", "mettrait", "mettrions", "mettriez", "mettraient"],
      subjonctifPresent: ["mette", "mettes", "mette", "mettions", "mettiez", "mettent"],
    },
  },
  attendre: {
    infinitive: "attendre",
    english: "to wait",
    group: "3rd group (-re)",
    importance: 3,
    startsWithVowel: true,
    tenses: {
      present: ["attends", "attends", "attend", "attendons", "attendez", "attendent"],
      passeCompose: ["ai attendu", "as attendu", "a attendu", "avons attendu", "avez attendu", "ont attendu"],
      imparfait: ["attendais", "attendais", "attendait", "attendions", "attendiez", "attendaient"],
      futurSimple: ["attendrai", "attendras", "attendra", "attendrons", "attendrez", "attendront"],
      conditionnelPresent: ["attendrais", "attendrais", "attendrait", "attendrions", "attendriez", "attendraient"],
      subjonctifPresent: ["attende", "attendes", "attende", "attendions", "attendiez", "attendent"],
    },
  },
};

const TIPS = [
  "Short daily sessions beat long cramming!",
  "Try writing sentences with new conjugations.",
  "Focus on être and avoir first — they're everywhere!",
  "The nous and vous forms often rhyme.",
  "Passé composé = avoir/être + past participle.",
  "Imparfait is for descriptions and habits.",
  "Subjonctif follows 'que' — que je sois...",
  "Conditional is like future stem + imparfait endings.",
  "Most -er verbs follow the same pattern!",
  "Practice speaking out loud for better memory.",
];

const ENCOURAGEMENTS = {
  correct: ["Parfait!", "Magnifique!", "Excellent!", "Bravo!", "Très bien!", "Super!", "C'est ça!", "Formidable!"],
  streak: ["You're on fire!", "Keep going!", "Unstoppable!", "Incroyable streak!"],
  levelUp: ["Level up!", "New level unlocked!", "You're making progress!"],
};
